language: python

python:
   - "3.6"
   - "3.7"
   - "3.8"

install:
   - pip install .
   - pip install pytest
   - pip install coverage
   - pip install coveralls

script:
   - pytest

after_success:
   - coverage run -m pytest
   - coverage report
   - coverage html
   - coveralls

notifications:
   email:
      on_success: change
      on_failure: always
